package edu.stankin.cogoalmain.db.entity;

import jakarta.persistence.GeneratedValue;
import jakarta.persistence.GenerationType;
import jakarta.persistence.Id;
import jakarta.persistence.MappedSuperclass;
import lombok.Getter;

import java.util.UUID;

/**
 * Entity whose UUID id is generated by the application on persist.
 */
@Getter
@MappedSuperclass
public abstract class GeneratedIdEntity extends BaseEntity {

    @Id
    @GeneratedValue(strategy = GenerationType.UUID)
    private UUID id;
}
